### ISSUE TITLE
uploaded Media File Not showing 

### ISSUE THREAD

**Issue by asad-pidroid** [app-generator/django-pixel-pro#1]
Settings : 
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(CORE_DIR, 'media')

in urls.py
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
![error](https://user-images.githubusercontent.com/112679930/216054694-3e53ae15-135d-4695-966f-1e3f9d836697.png)
getting 404 error

**Comment by app-generator** [comment]
Hello @asad-pidroid 

We acknowledged your ticket. 
Soon, an engineer will take a look.

**Comment by asad-pidroid** [comment]
have you gone through it?

**Comment by app-generator** [comment]
Hello @asad-pidroid 
Other things bump and this was deleted. 
Let me take a look right now and get back with some advice. 

ty!

**Comment by app-generator** [comment]
Hello @asad-pidroid 

Sorry for the delay. 
The documentation has been updated to cover this topic:

[How to manage Media Files in Django](https://docs.appseed.us/content/how-to/django-medial-files/) 

Let us know if you need further assistance.

**Comment by app-generator** [comment]
Closing.
