### ISSUE TITLE
Templates Pixel Pro and Volt not working anymore

### ISSUE THREAD

**Issue by dpvro** [app-generator/django-pixel-pro#1]
Hi, 
I was using for some time the Pixel Pro for my Django website and everything went well. But, I have tried to use the Volt Free to test it for dashboard and now my whole set of templates is not working. 

What I have done:
- I have installed the volt template and added in settings (you can see the picture with the project structure):
`INSTALLED_APPS = [
    'apps.admin',
    'django.contrib.admin',
    'django.contrib.auth',
    ....`
`#############################################################

STATIC_ROOT = os.path.join(CORE_DIR, 'core/staticfiles')
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(CORE_DIR, 'core/static'),
    os.path.join(CORE_DIR, 'apps/admin/static'),
)
#############################################################
#############################################################`
![Screenshot 2021-12-14 182101](https://user-images.githubusercontent.com/1090395/146048017-eeb2e8a9-c157-436f-b108-1e05588f7998.jpg)

- I have run on the server in the virtualenv the python manage.py collectstatic

And it did not worked. Then I tried a couple of things but still not working:

- I have recompiled with gulp the files from apps/admin/static/admin_volt/assets and run again collectstatic
- I have reinstalled the npm in apps/admin/static/admin_volt/assets
- I have recompiled with gulp the files from core/static/assets

Now, both templates Pixel Pro and Volt are not working anymore.

I am using: Ubuntu 20.04.3 LTS with Django 3.2.9, gulp CLI 2.3.0

Error log from nginx:

2021/12/14 17:27:07 [error] 7216#7216: *47 open() "......./core/static/admin_volt/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js" failed (2: No such file or directory), client: XXX.XXX.XXX.XXX, server: 138.197.104.93, request: "GET /static/admin_volt/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js HTTP/1.1", host: "138.197.104.93", referrer: "http://138.197.104.93/admin/"
2021/12/14 17:27:07 [error] 7216#7216: *47 open() "......./core/static/admin_volt/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js" failed (2: No such file or directory), client: XXX.XXX.XXX.XXX, server: 138.197.104.93, request: "GET /static/admin_volt/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js HTTP/1.1", host: "138.197.104.93", referrer: "http://138.197.104.93/admin/"
2021/12/14 17:27:07 [error] 7216#7216: *47 open() "......./core/static/admin_volt/assets/vendor/sweetalert2/dist/sweetalert2.all.min.js" failed (2: No such file or directory), client: XXX.XXX.XXX.XXX, server: 138.197.104.93, request: "GET /static/admin_volt/assets/vendor/sweetalert2/dist/sweetalert2.all.min.js HTTP/1.1", host: "138.197.104.93", referrer: "http://138.197.104.93/admin/"
2021/12/14 17:27:07 [error] 7216#7216: *47 open() "......./core/static/admin_volt/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js" failed (2: No such file or directory), client: XXX.XXX.XXX.XXX, server: 138.197.104.93, request: "GET /static/admin_volt/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js HTTP/1.1", host: "138.197.104.93", referrer: "http://138.197.104.93/admin/"
2021/12/14 17:27:08 [error] 7216#7216: *47 open() "......./core/static/admin_volt/assets/vendor/notyf/notyf.min.js" failed (2: No such file or directory), client: XXX.XXX.XXX.XXX, server: 138.197.104.93, request: "GET /static/admin_volt/assets/vendor/notyf/notyf.min.js HTTP/1.1", host: "138.197.104.93", referrer: "http://138.197.104.93/admin/"
2021/12/14 17:27:08 [error] 7216#7216: *47 open() "......./core/static/admin_volt/assets/vendor/simplebar/dist/simplebar.min.js" failed (2: No such file or directory), client: XXX.XXX.XXX.XXX, server: 138.197.104.93, request: "GET /static/admin_volt/assets/vendor/simplebar/dist/simplebar.min.js HTTP/1.1", host: "138.197.104.93", referrer: "http://138.197.104.93/admin/"
2021/12/14 17:27:08 [error] 7216#7216: *47 open() "......./core/static/admin_volt/assets/js/volt.js" failed (2: No such file or directory), client: XXX.XXX.XXX.XXX, server: 138.197.104.93, request: "GET /static/admin_volt/assets/js/volt.js HTTP/1.1", host: "138.197.104.93", referrer: "http://138.197.104.93/admin/"
2021/12/14 17:27:08 [error] 7216#7216: *47 open() "......./core/static/admin_volt/assets/js/scripts.js" failed (2: No such file or directory), client: XXX.XXX.XXX.XXX, server: 138.197.104.93, request: "GET /static/admin_volt/assets/js/scripts.js HTTP/1.1", host: "138.197.104.93", referrer: "http://138.197.104.93/admin/"

The test server can be seen,, is publicly accessible.

**Comment by app-generator** [comment]
Hello @dpvro, 

Thank you for using our products. 
We will try to assist and provide a solution. 

BR

**Comment by dpvro** [comment]
Thanks, 
Some more updates. 
I have checked the django webpage inside the virtualenv with runserver and the Volt app template works but the Pixel Pro is still not working. With Nginx+ gunicorn neither of both themes are working.

**Comment by dpvro** [comment]
Found the issue, at least a workaround. The files from /core/static/assets were not complete and the files copied in /core/staticfiles through collectstatic of course that are not complete.

My question is why by compiling with gulp the Pixel Pro template the core/static/assets folder does not contain all the files. Maybe I understood wrong the process, but please just let me know, how are all the files arriving in core/static/assets

**Comment by app-generator** [comment]
Hello @dpvro 

The Gulp scrip comes with a simple flow that compiles the SCSS files into the CSS. 
There is no active code or instructions that move the files.

- `core/static/assets/gulpfile.js` - Code chunk: 

```javascript
...
gulp.task('default', gulp.series('scss', 'minify:css')); 
...
```

**Comment by imankarimi** [comment]
Hello @dpvro 
I pull the [pixel pro](https://github.com/app-generator/priv-django-pixel-pro) and after that, I install the [Django volt admin](https://github.com/app-generator/django-admin-volt), And everything was OK.

So I think your problem is not this. please tell me what exactly you did.

**Comment by dpvro** [comment]
As I mentioned before, I have fixed the issue. Some files from /core/static were missing and of course that not all were used as static files. So, I have fixed the issue, and no problem are between Pixel Pro and Volt.

**Comment by app-generator** [comment]
Hello @dpvro!

Let us know if you need further assistance. 
Ty @imankarimi for your support. 

Closing.
