### ISSUE TITLE
css issue

### ISSUE THREAD

**Issue by stemcell000** [app-generator/django-pixel-pro#3]
Hi,
I installed the Django-pixel-pro kit as follow : 
1. export the GH_TOKEN
2. clone the DPP repo
3. cd django-pixel-pro and create & activate venv (env folder)
4. pip installl requirements. The theme seems to be correctly installed : 
<img width="253" alt="Capture d’écran 2023-04-21 à 19 32 10" src="https://user-images.githubusercontent.com/9267768/233699308-cfe39b17-bd24-4deb-9fbf-bd139a845b3b.png">
6. create migration & migrate (dm, dmm)
7. start server (drs)
This is what I have with any web browser : 
<img width="629" alt="Capture d’écran 2023-04-21 à 19 31 15" src="https://user-images.githubusercontent.com/9267768/233699467-42a346e4-006f-430a-bd25-b917891a5290.png">
It seems the css are not loaded. Would you please give me a hand ?
Thanks

**Comment by app-generator** [comment]
Hello @stemcell000 

I just tested the app on Windows plus a LIVE deployment on Render.
All looks good. 

https://django-pixel-pro-0sm4.onrender.com/

Our advice is to make a hard refresh on the browser (Shift + F5 in Chrome) to force the assets to reload. 
I suspect that the browser uses the pixel lite CSS, not the PRO version from the cache. 

In all cases, let us know your progress. 

`AppSeed team`

**Comment by stemcell000** [comment]
Thank you for your answer. Unfortunately, there is no change after a hard refresh on any browser (Firefox, Chrome, Safari).
I reinstall the kit and it doesn't change anything.
I get the following message when I open it : 
 "GET /static/css/pixel.css HTTP/1.1" 404 1798
and 
python manage.py findstatic "css/pixel.css
gets : No matching file found for 'css/pixel.css'.

I tried to use Docker :

env) (base) marc@macbook-pro cproject % docker-compose up --build                                      
[+] Building 2.6s (8/10)                                                                                         
 => [internal] load build definition from Dockerfile                                                        0.0s
 => => transferring dockerfile: 32B                                                                         0.0s
 => [internal] load .dockerignore                                                                           0.0s
 => => transferring context: 2B                                                                             0.0s
 => [internal] load metadata for docker.io/library/python:3.9                                               0.6s
 => [1/6] FROM docker.io/library/python:3.9@sha256:2d8875d28ca023a9056a828518adcdd634ba03740e1e3b197c06eb4  0.0s
 => => resolve docker.io/library/python:3.9@sha256:2d8875d28ca023a9056a828518adcdd634ba03740e1e3b197c06eb4  0.0s
 => [internal] load build context                                                                           0.3s
 => => transferring context: 1.17MB                                                                         0.3s
 => CACHED [2/6] COPY requirements.txt .                                                                    0.0s
 => CACHED [3/6] RUN pip install --upgrade pip                                                              0.0s
 => ERROR [4/6] RUN pip install --no-cache-dir -r requirements.txt                                          1.6s
------                                                                                                           
 > [4/6] RUN pip install --no-cache-dir -r requirements.txt:                                                     
#0 0.981 Collecting git+https://****@github.com/app-generator/priv-django-theme-pixel-pro (from -r requirements.txt (line 5))                                                                                                     
#0 0.982   Cloning https://****@github.com/app-generator/priv-django-theme-pixel-pro to /tmp/pip-req-build-55fv9ikn
#0 0.987   Running command git clone --filter=blob:none --quiet 'https://****@github.com/app-generator/priv-django-theme-pixel-pro' /tmp/pip-req-build-55fv9ikn
#0 1.407   fatal: could not read Password for 'https://${GITHUB_TOKEN}@github.com': No such device or address
#0 1.430   error: subprocess-exited-with-error
#0 1.430   
#0 1.430   × git clone --filter=blob:none --quiet 'https://****@github.com/app-generator/priv-django-theme-pixel-pro' /tmp/pip-req-build-55fv9ikn did not run successfully.
#0 1.430   │ exit code: 128
#0 1.430   ╰─> See above for output.
#0 1.430   
#0 1.430   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 1.433 error: subprocess-exited-with-error
#0 1.433 
#0 1.433 × git clone --filter=blob:none --quiet 'https://****@github.com/app-generator/priv-django-theme-pixel-pro' /tmp/pip-req-build-55fv9ikn did not run successfully.
#0 1.433 │ exit code: 128
#0 1.433 ╰─> See above for output.
#0 1.433 
#0 1.433 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: executor failed running [/bin/sh -c pip install --no-cache-dir -r requirements.txt]: exit code: 1

Sorry for asking your help again.

**Comment by app-generator** [comment]
Hello @stemcell000 

I just invite you to the private repo:

https://github.com/app-generator/priv-django-theme-pixel-pro/invitations

Once the invitation is accepted, remove the GITHUB_TOken from the `requirements.txt` file as shown below:

`git+https://github.com/app-generator/priv-django-theme-pixel-pro`

Let us know if the manual installation works after this change.

**Comment by stemcell000** [comment]
Hello app-generator,

It did not work. Same result here.

**Comment by app-generator** [comment]
Hello @stemcell000 

Something is not ok. If possible, please record and upload an unlisted video on YouTube. 
Tomorrow, we will do the same. 

Please reply with the following information:

- Your Operating system
- The editor you're using (if any)
- The terminal type (PowerShell, CMD, Xterm ...)
- Python Version 
- The manual build steps 
  - NOTE: Docker scripts are not updated with the GITHUB_TOKEN because we can't save on GitHub such information 

The product passed all acceptance tests and is also used by many developers and companies. 

We are waiting for your input. 
Ty!

**Comment by stemcell000** [comment]
Hello,
sorry I can't make a video on you tube for this. I just followed the steps in the "HOW-TO-USE-Django-pixel-pro.md" doc.
- macOS Monterey version 12.6
- No editor
- I tried fresh installation using Terminal, iTerm, visual studio
- Python version 3.11.3
I noticed the following change :
[1.0.1] 2023-04-21### Changes- Update Settings  - Added Local Template Directory
and python manage.py findstatic "css/pixel.css" still returns 'No matching file found for 'css/pixel.css'.

**Comment by stemcell000** [comment]
I managed to install it and make it work. I think I found the reason why it did not work is because I previously installed the package globally by mistakes (python manage.py findstatic "" showed a wrong location in my Library directory). 
Thank you very much for your help.

**Comment by app-generator** [comment]
Hello @stemcell000 

Glad it worked. 
Let us know anytime if you need further assistance. 

Adrian @ [AppSeed Support](https://appseed.us/support/)
